name: Webhook trigger

on:
  push:
    branches: [ 'master' ]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.WEBHOOK_TOKEN }}
        run: |
          curl -vv "http://akora.net:8787/akora-net-update?token=$SUPER_SECRET"
